language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: TkOppYGwdiKnnGilAkcICJMmATdaQJ5ce+fxAVIu2Ak2lyO7rJjtHZf52l+oRiVTLLerM5CyeXetko5IobAWdGqLZAN9A38G73N35JuHK/gU5mAzXen76eAJOKNckGPEzZrpDO9CcFaLmS6bPgFTcADQOWX+yGFWGx+AbWbFTqrctNLR+9e7pO3qRAYEo4z5STsumFjSGzGYlibdrtih+MVpK8WmyPA3hIUhnF3CAm19aes3lDhCi0ncyGZhA23ijF6Xz0awvXHspUmIunv2OwUE+1YJQX0zlwQeFij/rcsPYJAv13cqjqxNzM0HFm4jWHeepes3212b1NRGcwq+m/Q5swr7wEzVQ7d1peqtflZcJda+SI3eFDnNYmJxq7JAS1LfhlNlz/Xd7CUR6RCjb5bRdafdTGZ6u17MTe42GUpqx7TTYUPOlFrtK8f2gh8pBhh7i1geICQqujl8Ma645IwP20uCs5Nl9xVMYqMvvPuiKxweFz1qRcmNtvAMX2DSCzNeUmVwLnnzbeZJ3+9HJy7SqLSlsTTeyQwrijd2vOgHkEUFfzFQK9MUDZrEt6/Wi+AIiWkFWCgAAZl+cN6K0tnPVUUKqREe2YRdVX+lQLznd1P8etJl8skIA3uS6gB2/7v3PMJ4zQyA166772REyi0S3H6NP/kX4GMKItq5EMY=
