language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: YQlxqobn1stgW00oSCHrgAMKgHYaX3BborVq1Jpp41AzLRoXTqAIAQL1zI2W9Uo9fgZ0tEkDEbF6w6OacZnFkfWfbORoLola4oZcnSw59UE9fn79oevSpvwwcUEj7aQ6/zXLMZ+cDvvVlQiLx0IRvtxhXAgmbBMBEKOqzEfKvUxcws0uris/l4ENpS6Irvok0jyl960LLQqRGGqckJRAQ93ro8LSeNMv/MyUGSSr7wlErp2v2scn+/vax9+pL12zYJAJKgnDru4NAy2ssNqlE01rLkLAhlVp34OQ9nBEQi2YaBdqmY/ADhIsZNIvPsiBlQI0OOCLFBg2HvG1HB2hu4lt78fQOYQZqcjbriUnZH4ZJS6+N0i0tpZuWeH0mye+YTu354SNnJ2Py/diK9NpBDfOHbAdrQ8yz4TIS612r/cm371VBUGCe07u1mAs501BtfX9Oin0pS3hTxSfRXynEULMtgfDATcpJyE9eWlMMEJwUPpr2P4F4zG7HiyXYLYoorgPXWetuF760EgIyMMHNS/mnJh/JKjbOwpe8YRUdv8sG/0rP7q+e0UUyhyl93hLkOjcSdOMu+TEdXUdfHIEQhX+cjbtT7vDcNJ50ah3ghnxoTSTE/iHMw03K92fRsc4zgy85HtASWGsG4Mzf8s+TgLhGxUaQPTM0L7Toh7GSIE=
